[package]
name = "pnwkit"
version = "0.1.0"
edition = "2021"

[dependencies.pnwkit-core]
path = "../pnwkit-core"
default-features = false

[dependencies.reqwest]
version = "0.11"
features = ["rustls-tls"]
optional = true
default-features = false

[dependencies.async-tungstenite]
version = "0.17"
features = ["tokio-native-tls"]
optional = true

[features]
default = []
async = ["reqwest", "pnwkit-core/async"]
sync = ["reqwest", "reqwest/blocking", "pnwkit-core/sync"]
subscriptions = ["reqwest", "pnwkit-core/subscriptions", "dep:async-tungstenite"]
