[package]
name = "pnwkit"
version = "3.0.0-alpha.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/mrvillage/pnwkit"
description = "pnwkit bindings for Rust."

[dependencies.pnwkit-core]
path = "../pnwkit-core"
default-features = false

[dependencies.reqwest]
version = "0.11"
features = ["rustls-tls"]
optional = true
default-features = false

[dependencies.tokio-tungstenite]
version = "0.17"
features = ["native-tls"]
optional = true

[dependencies.tokio]
version = "1.20"
optional = true
features = ["time"]

[dependencies.futures-util]
version = "0.3"
optional = true
features = []

[features]
default = []
async = ["reqwest", "pnwkit-core/async", "dep:tokio"]
sync = ["reqwest", "reqwest/blocking", "pnwkit-core/sync"]
subscriptions = ["reqwest", "pnwkit-core/subscriptions", "dep:tokio-tungstenite", "dep:tokio", "dep:futures-util"]
